export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <title>Miku Page</title>
      <body>{children}</body>
    </html>
  )
}
